name: Auto PRs from Staging

on:
  pull_request:
    branches: [ main ]
    types:
      - closed

jobs:
  auto-prs:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GitHubActionsToken }}

    steps:
      - name: Check out code
        uses: actions/checkout@main

      - name: Create PR to Demo
        if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'staging_cep'
        run: |
          title=$(gh pr view ${{ github.event.pull_request.number }} --json title -q .title)
          pr_url=$(gh pr create --base demo --head staging_cep --title "Merge changes from staging_cep to demo: $title" --body "Auto PR from GitHub Actions")
          PR_NUMBER=$(echo $pr_url | awk -F'/' '{print $NF}')
          echo "$(gh pr view $PR_NUMBER --json mergeable)"
          MERGEABLE=$(gh pr view $PR_NUMBER --json mergeable -q .mergeable)
          echo "$MERGEABLE"
          if [ "$MERGEABLE" == "MERGEABLE" ]; then
            echo "PR mergeable."
            gh pr merge $PR_NUMBER --merge
          else
            echo "::error::PR has conflicts."
            exit 1
          fi
#          if [ "$conflicts" == "null" ]; then
#            echo "PR has conflicts."
#          else
#            echo "PR is mergeable. "
#            gh pr merge $PR_NUMBER --merge --auto
#          fi

#      - name: Create PR to Preprod
#        if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'staging_cep'
#        run: |
#          title=$(gh pr view ${{ github.event.pull_request.number }} --json title -q .title)
#          pr_url=$(gh pr create --base preprod --head staging_cep --title "Merge changes from staging_cep to preprod: $title" --body "Auto PR from GitHub Actions")
#          PR_NUMBER=$(echo $pr_url | awk -F'/' '{print $NF}')
#          gh pr merge $PR_NUMBER --merge
#           echo "$(gh pr view $PR_NUMBER --json number)"
          
