name: Push Event Workflow

on:
  # Triggers the workflow on pull request events only for the main branch
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    strategy:
      fail-fast: false # All tests should run even if some fails
      matrix:
        os: [ubuntu-latest]
        python-version:
          - "3.11"
    name: Unit Tests
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: python -m pip install -r requirements.txt

      - name: Run tests
        run: FLASK_ENV=test coverage run -m unittest test.test_suite


