name: Unit Tests Workflow

on:
  # Triggers the workflow on pull request events only for the main branch
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    strategy:
      fail-fast: false # All tests should run even if some fails
      matrix:
        os: [ubuntu-latest]
        python-version:
          - "3.11"
    name: Unit Tests
    runs-on: ${{ matrix.os }}
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: testDbUser
          POSTGRES_PASSWORD: 12345
          POSTGRES_DB: myTestDb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip dependencies

      - name: Install Dependencies
        run: python -m pip install -r requirements.txt

      - name: Run tests
        run: FLASK_ENV=test coverage run -m unittest test.test_suite
